describe("Timepicker directive tests: ", function() {
  var mockScope
  var compileService
  
  beforeEach(angular.mock.module("timepicker"))

  beforeEach(angular.mock.inject(function($rootScope, $compile) {
    mockScope = $rootScope.$new()
    compileService = $compile
	mockScope.timeValue = new Date()
    mockScope.minTime = new Date()
    mockScope.minTime.setHours(9)
    mockScope.minTime.setMinutes(0)
    mockScope.minTime.setSeconds(0)
    mockScope.maxTime = new Date()
    mockScope.maxTime.setHours(17)
    mockScope.maxTime.setMinutes(30)
    mockScope.maxTime.setSeconds(0)
  }))

  it("Generates default timepicker elements", function(){
    var compileFn = compileService("<div my-timepicker value='timeValue'></div>")
    var elem = compileFn(mockScope)
    mockScope.$digest()
    expect(elem.children().length).toEqual(4)
  })

  it("Generates timepicker elements for format HHmmss", function(){
    var compileFn = compileService("<div my-timepicker format='HHmmss' value='timeValue'></div>")
    var elem = compileFn(mockScope)
    mockScope.$digest()
    expect(elem.text()).toEqual('.timepicker {border-radius:0; width: auto; display: inline-block;}')
    expect(elem.children().length).toEqual(4)
  })

  it("Generates timepicker elements for format Hours: HH Minutes: mm", function(){
    var compileFn = compileService("<div my-timepicker format='Hours: HH Minutes: mm' value='timeValue'></div>")
    var elem = compileFn(mockScope)
    mockScope.$digest()
    expect(elem.text()).toEqual('.timepicker {border-radius:0; width: auto; display: inline-block;}Hours:  Minutes: ')
    expect(elem.children().length).toEqual(3)
  })

  it("Generates timepicker elements for format hhmmss", function(){
    mockScope.timeValue = new Date()
    mockScope.timeValue.setHours(18)
    var compileFn = compileService("<div my-timepicker format='hhmmss' value='timeValue'></div>")
    var elem = compileFn(mockScope)
    mockScope.$digest()
    expect(elem.children().length).toEqual(5)
  })

  it("sets a valid time", function(){
    mockScope.timeValue = new Date()
    mockScope.timeValue.setHours(12)
    mockScope.minTime = new Date()
    mockScope.minTime.setHours(0)
    mockScope.minTime.setMinutes(0)
    mockScope.minTime.setSeconds(0)
    mockScope.maxTime = new Date()
    mockScope.maxTime.setHours(23)
    mockScope.maxTime.setMinutes(59)
    mockScope.maxTime.setSeconds(59)
    var compileFn = compileService("<div my-timepicker min-time='minTime' max-time='maxTime' value='timeValue'></div>")
    var elem = compileFn(mockScope)
    mockScope.$digest()
    expect(mockScope.timeValue.getHours()).toEqual(12)
  })

  it("Generates timepicker elements with timeValue < minTime", function(){
    mockScope.timeValue = new Date()
    mockScope.timeValue.setHours(18)
    mockScope.timeValue.setMinutes(0)
    mockScope.timeValue.setSeconds(0)
    mockScope.minTime = new Date()
    mockScope.minTime.setHours(12)
    mockScope.minTime.setMinutes(0)
    mockScope.minTime.setSeconds(0)
    mockScope.maxTime = new Date()
    mockScope.maxTime.setHours(23)
    mockScope.maxTime.setMinutes(59)
    mockScope.maxTime.setSeconds(59)
    var compileFn = compileService("<div my-timepicker min-time='minTime' max-time='maxTime' value='timeValue'></div>")
    var elem = compileFn(mockScope)
    mockScope.$digest()
    expect(mockScope.timeValue.getHours()).toEqual(18)
    mockScope.timeValue.setHours(13)
    mockScope.$digest()
    expect(mockScope.timeValue.getHours()).toEqual(13)
    mockScope.timeValue.setHours(6)
    mockScope.$digest()
    expect(mockScope.timeValue.getHours()).toEqual(13)
  })

  it("Generates timepicker elements with timeValue > maxTime", function(){
    mockScope.timeValue = new Date()
    mockScope.timeValue.setHours(0)
    mockScope.timeValue.setMinutes(0)
    mockScope.timeValue.setSeconds(0)
    mockScope.minTime = new Date()
    mockScope.minTime.setHours(0)
    mockScope.minTime.setMinutes(0)
    mockScope.minTime.setSeconds(0)
    mockScope.maxTime = new Date()
    mockScope.maxTime.setHours(6)
    mockScope.maxTime.setMinutes(0)
    mockScope.maxTime.setSeconds(0)
    var compileFn = compileService("<div my-timepicker min-time='minTime' max-time='maxTime' value='timeValue'></div>")
    var compileFn = compileService("<div my-timepicker min-time='minTime' max-time='maxTime' value='timeValue'></div>")
    var elem = compileFn(mockScope)
    mockScope.$digest()
    expect(mockScope.timeValue.getHours()).toEqual(0)
    mockScope.timeValue.setHours(1)
    mockScope.$digest()
    expect(mockScope.timeValue.getHours()).toEqual(1)
    mockScope.timeValue.setHours(12)
    mockScope.$digest()
    expect(mockScope.timeValue.getHours()).toEqual(1)
  })
})
